# print("hello world")   
# print(10,20,40,sep='@',end='@')   
# print(5,10,sep='@')    
# print('#','#',sep='%',end='%')
# print(1,2,3,sep='$',end='^')     
# a=eval(input('enter a value: ')) 
# print(a+50)
# b=list(input('enter a value: '))
# print(b)
# c=eval(input('enter a value: ')) 
# print(c)
d=eval(input('enter a value: ')) 
print(d+[100])
print(type(d))